server:
  port: 8080
spring:
  datasource:
    username: root
    password: RomaLank$n_08
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    # show-sql: true
indexing-settings:
  sites:
    #- url: https://www.ilovesupersport.ru
    #  name: ILoveSupersport.ru
    - url: https://www.playback.ru
      name: PlayBack.Ru
    #- url: https://guitarlessons.timsto.ru
    #  name: Гитарная школа Тимофея Столярова